# Generated by Django 5.0.2 on 2024-02-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Mensagem',
        ),
    ]
