# Generated by Django 5.0.2 on 2024-02-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_rename_contact_mensagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Contact',
        ),
    ]
